name: forecast_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  # scoped model
  scoped_model: ^1.0.1
  # dependency injection
  get_it: ^3.1.0
  # http client
  http: ^0.12.0+3
  # flare animations
  flare_flutter: ^1.8.3
  # shared preferences
  shared_preferences: ^0.5.6
  # speed dial fab
  flutter_speed_dial: ^1.2.5
  # date
  intl: ^0.16.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/BackgroundSky.flr
    - assets/cloudy-day.flr
    - assets/cloudy-night.flr
    - assets/foggy-weather.flr
    - assets/heavy-rainy-day.flr
    - assets/heavy-rainy-night.flr 
    - assets/moon-not.flr
    - assets/snowy.flr
    - assets/sunny-day.flr
    - assets/thunder-rainy-day.flr
    - assets/thunder-rainy-night.flr
    - assets/windy.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
